"""initial_schema

Revision ID: 382438d6a70e
Revises: 
Create Date: 2026-03-09 11:24:54.262621
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '382438d6a70e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_api_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_api_settings_provider'), 'ai_api_settings', ['provider'], unique=False)
    op.create_table('brand_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('style_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_stock_pool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_name', sa.String(length=200), nullable=False),
    sa.Column('stocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_stock_pool_pool_name'), 'company_stock_pool', ['pool_name'], unique=False)
    op.create_table('crawling_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawling_jobs_source_type'), 'crawling_jobs', ['source_type'], unique=False)
    op.create_index(op.f('ix_crawling_jobs_status'), 'crawling_jobs', ['status'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('theme_name', sa.String(length=200), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('news_summary', sa.Text(), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_themes_theme_name'), 'stock_themes', ['theme_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('commission_calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('calc_type', sa.String(length=100), nullable=False),
    sa.Column('source_file_path', sa.String(length=500), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_calculations_status'), 'commission_calculations', ['status'], unique=False)
    op.create_index(op.f('ix_commission_calculations_user_id'), 'commission_calculations', ['user_id'], unique=False)
    op.create_table('content_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='card_news / report / cover_promo'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('content_input', sa.Text(), nullable=True),
    sa.Column('brand_setting_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_setting_id'], ['brand_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_projects_brand_setting_id'), 'content_projects', ['brand_setting_id'], unique=False)
    op.create_index(op.f('ix_content_projects_status'), 'content_projects', ['status'], unique=False)
    op.create_index(op.f('ix_content_projects_user_id'), 'content_projects', ['user_id'], unique=False)
    op.create_table('portfolio_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rebalancing_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_analyses_status'), 'portfolio_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_analyses_user_id'), 'portfolio_analyses', ['user_id'], unique=False)
    op.create_table('stock_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('selected_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_recommendations_status'), 'stock_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_stock_recommendations_user_id'), 'stock_recommendations', ['user_id'], unique=False)
    op.create_table('commission_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculation_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('detail_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['commission_calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_results_calculation_id'), 'commission_results', ['calculation_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('ai_text_content', sa.Text(), nullable=True),
    sa.Column('generated_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_project_id'), 'content_versions', ['project_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['portfolio_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_analysis_id'), 'portfolio_items', ['analysis_id'], unique=False)
    op.create_table('recommended_stocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('return_3m', sa.Float(), nullable=True),
    sa.Column('return_6m', sa.Float(), nullable=True),
    sa.Column('institutional_buy', sa.Float(), nullable=True),
    sa.Column('foreign_buy', sa.Float(), nullable=True),
    sa.Column('is_top5', sa.Boolean(), nullable=False),
    sa.Column('analysis_report', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['stock_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_stocks_recommendation_id'), 'recommended_stocks', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommended_stocks_recommendation_id'), table_name='recommended_stocks')
    op.drop_table('recommended_stocks')
    op.drop_index(op.f('ix_portfolio_items_analysis_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_content_versions_project_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_commission_results_calculation_id'), table_name='commission_results')
    op.drop_table('commission_results')
    op.drop_index(op.f('ix_stock_recommendations_user_id'), table_name='stock_recommendations')
    op.drop_index(op.f('ix_stock_recommendations_status'), table_name='stock_recommendations')
    op.drop_table('stock_recommendations')
    op.drop_index(op.f('ix_portfolio_analyses_user_id'), table_name='portfolio_analyses')
    op.drop_index(op.f('ix_portfolio_analyses_status'), table_name='portfolio_analyses')
    op.drop_table('portfolio_analyses')
    op.drop_index(op.f('ix_content_projects_user_id'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_status'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_brand_setting_id'), table_name='content_projects')
    op.drop_table('content_projects')
    op.drop_index(op.f('ix_commission_calculations_user_id'), table_name='commission_calculations')
    op.drop_index(op.f('ix_commission_calculations_status'), table_name='commission_calculations')
    op.drop_table('commission_calculations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_themes_theme_name'), table_name='stock_themes')
    op.drop_table('stock_themes')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_crawling_jobs_status'), table_name='crawling_jobs')
    op.drop_index(op.f('ix_crawling_jobs_source_type'), table_name='crawling_jobs')
    op.drop_table('crawling_jobs')
    op.drop_index(op.f('ix_company_stock_pool_pool_name'), table_name='company_stock_pool')
    op.drop_table('company_stock_pool')
    op.drop_table('brand_settings')
    op.drop_index(op.f('ix_ai_api_settings_provider'), table_name='ai_api_settings')
    op.drop_table('ai_api_settings')
    # ### end Alembic commands ###
