"""add quantity purchase_price current_price to holdings

Revision ID: 6f86cc96bd7e
Revises: d4e5f6a7b8c9
Create Date: 2026-03-19 14:22:51.433202
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6f86cc96bd7e'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_holdings', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('current_price', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_portfolio_snapshots_account_id'), table_name='portfolio_snapshots')
    op.create_index(op.f('ix_portfolio_snapshots_client_account_id'), 'portfolio_snapshots', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_suggestions_account_id'), 'portfolio_suggestions', ['account_id'], unique=False)
    op.drop_constraint(op.f('uq_product_master_product_name'), 'product_master', type_='unique')
    op.drop_index(op.f('ix_product_master_product_name'), table_name='product_master')
    op.create_index(op.f('ix_product_master_product_name'), 'product_master', ['product_name'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_master_product_name'), table_name='product_master')
    op.create_index(op.f('ix_product_master_product_name'), 'product_master', ['product_name'], unique=False)
    op.create_unique_constraint(op.f('uq_product_master_product_name'), 'product_master', ['product_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_portfolio_suggestions_account_id'), table_name='portfolio_suggestions')
    op.drop_index(op.f('ix_portfolio_snapshots_client_account_id'), table_name='portfolio_snapshots')
    op.create_index(op.f('ix_portfolio_snapshots_account_id'), 'portfolio_snapshots', ['client_account_id'], unique=False)
    op.drop_column('portfolio_holdings', 'current_price')
    op.drop_column('portfolio_holdings', 'purchase_price')
    op.drop_column('portfolio_holdings', 'quantity')
    # ### end Alembic commands ###
