"""add_total_deposit_withdrawal_to_holdings

Revision ID: 9da2688a7673
Revises: da46db5e3cf1
Create Date: 2026-03-23 17:33:37.929483
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9da2688a7673'
down_revision: Union[str, None] = 'da46db5e3cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_holdings', sa.Column('total_deposit', sa.Float(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('total_withdrawal', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_holdings', 'total_withdrawal')
    op.drop_column('portfolio_holdings', 'total_deposit')
    # ### end Alembic commands ###
