"""add foreign_deposit_amount total_assets to snapshots

Revision ID: a9fe37064980
Revises: 6f86cc96bd7e
Create Date: 2026-03-19 15:07:01.992952
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a9fe37064980'
down_revision: Union[str, None] = '6f86cc96bd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_snapshots', sa.Column('foreign_deposit_amount', sa.Float(), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('total_assets', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_snapshots', 'total_assets')
    op.drop_column('portfolio_snapshots', 'foreign_deposit_amount')
    # ### end Alembic commands ###
